name: Maven build
on: [push]
jobs:
  build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v4
       - uses: actions/setup-java@v4
         with:
          distribution: 'temurin'
          java-version: '17'
       - name: print status
         run: echo"push detected"
       - name: Build with maven
         run: mvn clean install


