name: Maven build
on: [push]
jobs:
  build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v4
       - name: print status
         run: echo"push detected"




